// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace QuanLyHoiVienGym.Models;

public partial class QuanLyHoiVienGym_EFContext : DbContext
{
    public QuanLyHoiVienGym_EFContext(DbContextOptions<QuanLyHoiVienGym_EFContext> options)
        : base(options)
    {
    }
    public QuanLyHoiVienGym_EFContext()
    {
    }

    // THÊM hàm này
    protected override void OnConfiguring(
        DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            optionsBuilder.UseSqlServer(
                "Server=MSI\\SQLEXPRESS;Database=QuanLyHoiVienGym_EF;Trusted_Connection=True;TrustServerCertificate=True;");
        }
    }
    public virtual DbSet<HoiVien> HoiViens { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<HoiVien>(entity =>
        {
            entity.HasKey(e => e.MaHv).HasName("PK__HoiVien__2725A6D289EDABA9");

            entity.ToTable("HoiVien");

            entity.Property(e => e.MaHv).HasColumnName("MaHV");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.HangThanhVien)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Basic");
            entity.Property(e => e.HoTen)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.NgayDangKy)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Sdt)
                .IsRequired()
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasColumnName("SDT");
            entity.Property(e => e.TrangThai).HasDefaultValue(true);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}